### ISSUE TITLE
Not setting excluded and appended results into Finder error

### ISSUE THREAD

**Issue by mawalu** [DarkGhostHunter/Laraload#14]
I did not manage to get this package working without manually removing the `getFilesFromFinder` from the [preloader](https://github.com/DarkGhostHunter/Preloader/blob/master/src/Preloader.php#L90). It seems to me that Laraload somehow passes the `excluded` and `appended` values in way that makes Preload always use them as finder.

With the default config and no modification in the Loader code this is the logged error:
```
local.ERROR: You must call one of in() or append() methods before iterating over a Finder. {"exception":"[object] (LogicException(code: 0): You must call one of in() or append() methods before iterating over a Finder. at /var/www/vendor/symfony/finder/Finder.php:623)
[stacktrace]
#0 /var/www/vendor/darkghosthunter/preloader/src/ManagesFiles.php(95): Symfony\\Component\\Finder\\Finder->getIterator()
#1 /var/www/vendor/darkghosthunter/preloader/src/Preloader.php(90): DarkGhostHunter\\Preloader\\Preloader->getFilesFromFinder(Object(Symfony\\Component\\Finder\\Finder))
#2 /var/www/vendor/darkghosthunter/preloader/src/Preloader.php(77): DarkGhostHunter\\Preloader\\Preloader->prepareLister()
#3 /var/www/vendor/darkghosthunter/preloader/src/Preloader.php(170): DarkGhostHunter\\Preloader\\Preloader->getList()
#4 /var/www/vendor/darkghosthunter/preloader/src/Preloader.php(155): DarkGhostHunter\\Preloader\\Preloader->prepareCompiler('/var/www/storag...')
#5 /var/www/vendor/darkghosthunter/preloader/src/Preloader.php(105): DarkGhostHunter\\Preloader\\Preloader->performWrite('/var/www/storag...')
#6 /var/www/vendor/darkghosthunter/laraload/src/Laraload.php(97): DarkGhostHunter\\Preloader\\Preloader->writeTo('/var/www/storag...')
#7 /var/www/vendor/darkghosthunter/laraload/src/Http/Middleware/LaraloadMiddleware.php(59): DarkGhostHunter\\Laraload\\Laraload->generate()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(212): DarkGhostHunter\\Laraload\\Http\\Middleware\\LaraloadMiddleware->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#9 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(183): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#10 /var/www/public/index.php(60): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#11 {main}
"}
```

**Comment by DarkGhostHunter** [comment]
I'll have to programmatically set the excluded and appended files to the preloader if the variables are present (callback or array).

Since there are always present, it automatically creates a Finder instance. with an empty array. Weird, because when you issue empty array it enforces "in" and "files" automatically.

I'll have to replicate this

**Comment by DarkGhostHunter** [comment]
Found that is a problem with the Preloader itself. I will update the Preloader and then this package.

**Comment by DarkGhostHunter** [comment]
Fixed in [Preloader v2.0.1](https://github.com/DarkGhostHunter/Preloader/releases/tag/v2.0.1) and [Laraload v2.0.1](https://github.com/DarkGhostHunter/Laraload/releases/tag/v2.0.1).

**Comment by mawalu** [comment]
Thanks for the fix and the new release

**Comment by DarkGhostHunter** [comment]
> Thanks for the fix and the new release

👍
